# Generated by Django 5.2.17 on 2026-09-23 09:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("checksum", models.CharField(max_length=64, unique=True)),
                ("source_dir", models.TextField()),
                ("customer_count", models.PositiveIntegerField()),
                ("summary", models.JSONField(default=dict)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-imported_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("queued", "В очереди"),
                            ("running", "Выполняется"),
                            ("completed", "Завершён"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменён"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                (
                    "budget",
                    models.DecimalField(
                        decimal_places=2, default=100000, max_digits=10
                    ),
                ),
                ("max_contacts", models.PositiveIntegerField(default=15000)),
                ("max_pilots", models.PositiveSmallIntegerField(default=20)),
                ("seed", models.PositiveIntegerField(default=42)),
                ("strategy", models.CharField(default="baseline", max_length=16)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="campaigns.dataset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
