# Generated by Django 5.2.17 on 2026-09-23 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.TextField()),
                ('profile', models.JSONField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='campaigns.dataset')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dataset', 'id_number'), name='unique_subscriber_per_dataset')],
            },
        ),
    ]
