# Generated by Django 5.2.7 on 2026-09-23 12:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "campaigns",
            "0002_campaignrun_cancel_requested_campaignrun_error_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="campaignrun",
            name="constraints",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="campaignrun",
            name="parent_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="derived_runs",
                to="campaigns.campaignrun",
            ),
        ),
        migrations.CreateModel(
            name="TeamSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("last_event_id", models.PositiveBigIntegerField(default=0)),
                ("public_state", models.JSONField(default=dict)),
                ("engine_state", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_snapshots",
                        to="campaigns.campaignrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_id", models.CharField(max_length=128)),
                ("actor_id", models.CharField(max_length=16)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("title", models.CharField(max_length=255)),
                ("artifact_ids", models.JSONField(default=list)),
                ("evidence_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_tasks",
                        to="campaigns.campaignrun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamArtifact",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("type", models.CharField(max_length=32)),
                ("title", models.CharField(max_length=255)),
                ("data", models.JSONField(default=dict)),
                ("evidence_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_artifacts",
                        to="campaigns.campaignrun",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="artifacts",
                        to="campaigns.teamtask",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamCommand",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(max_length=32)),
                ("parameters", models.JSONField(default=dict)),
                ("idempotency_key", models.CharField(max_length=255)),
                ("request_hash", models.CharField(max_length=64)),
                ("status", models.CharField(default="queued", max_length=16)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_commands",
                        to="campaigns.campaignrun",
                    ),
                ),
                (
                    "snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commands",
                        to="campaigns.teamsnapshot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "idempotency_key"),
                        name="unique_team_command_run_key",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="teamtask",
            constraint=models.UniqueConstraint(
                fields=("run", "task_id"), name="unique_team_task_run_id"
            ),
        ),
    ]
