# Generated by Django 5.2.17 on 2026-09-23 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0003_campaignrun_constraints_campaignrun_parent_run_and_more"),
        ("campaigns", "0003_merge_subscriber_execution"),
    ]

    operations = []
